#!/usr/bin/env python3
"""One-time scrape: read each existing /<slug>/index.html agent page and pull the
handful of fields that actually vary per agent into _build/agents.json.

After this runs and is spot-checked, agents.json + agent_template.html become the
single source of truth and the per-agent HTML files are regenerated by generate_agents.py.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Agents stored as a root-level <slug>.html file instead of a <slug>/index.html
# directory. These use root-relative asset paths (wp-content/...) which must be
# rewritten to the ../wp-content/... form the slug-dir template expects.
ROOT_FILE_AGENTS = {"mindy-walker": "mindy-walker.html"}

# Top-level dirs that are site sections, not agents.
NON_AGENT = {
    "about-us", "areas", "articles", "comments", "contact-us", "feed", "cdn-cgi",
    "idx", "join-our-brokerage", "management-team", "mortgage-calculator",
    "our-agents", "our-office", "sell", "wp-content", "wp-includes", "wp-json",
    "_build",
}

def agent_slugs():
    for name in sorted(os.listdir(ROOT)):
        path = os.path.join(ROOT, name)
        if not os.path.isdir(path):
            continue
        if name in NON_AGENT or name.startswith("."):
            continue
        if os.path.exists(os.path.join(path, "index.html")):
            yield name

def search(pattern, text, group=1, flags=re.DOTALL):
    m = re.search(pattern, text, flags)
    return m.group(group).strip() if m else None

def extract(slug, html):
    rec = {"slug": slug}

    # WordPress page id (from canonical/shortlink: ../index.html%3Fp=1277.html)
    rec["wp_id"] = search(r"%3Fp=(\d+)\.html", html)

    # Display name (cleanest from <title>NAME &#8211; Horizon Realty</title>)
    rec["name"] = search(r"<title>(.*?)\s*&#8211;\s*Horizon Realty</title>", html)

    # Role / subtitle: first <h4> heading inside the content (e.g. "Sales Associate")
    rec["title"] = search(
        r'elementor-widget-heading[^>]*>\s*<div class="elementor-widget-container">\s*'
        r'<h4 class="elementor-heading-title elementor-size-default">(.*?)</h4>',
        html,
    )

    # Photo: the agent headshot image widget. A few pages prepend a Horizon banner
    # logo image, so skip any banner/logo and take the first real headshot.
    img = None
    candidates = re.findall(
        r'elementor-widget-image[^>]*>\s*<div class="elementor-widget-container">\s*'
        r'(?:<a[^>]*>\s*)?(<img[^>]*?/>)',
        html, re.DOTALL,
    )
    for cand in candidates:
        src = search(r'\ssrc="([^"]+)"', cand)
        if src and re.search(r"Banner|Logo", src, re.IGNORECASE):
            continue
        img = cand
        break
    if img:
        rec["photo"] = search(r'\ssrc="([^"]+)"', img)
        rec["photo_srcset"] = search(r'\ssrcset="([^"]+)"', img)
        rec["photo_width"] = search(r'\swidth="([^"]+)"', img)
        rec["photo_height"] = search(r'\sheight="([^"]+)"', img)
    else:
        rec["photo"] = rec["photo_srcset"] = None

    # "Contact" icon-list link (Cloudflare-obfuscated email)
    rec["contact_href"] = search(
        r'<ul class="elementor-icon-list-items">.*?<a href="([^"]+)".*?icon-envelope2',
        html,
    )

    # Bio: inner HTML of the text-editor widget container (also holds office/email)
    rec["bio_html"] = search(
        r'widget_type="text-editor\.default">\s*<div class="elementor-widget-container">\s*(.*?)\s*</div>\s*</div>',
        html,
    )

    return rec

_STRIP_DOTS = re.compile(r"(?:\.\./)+(wp-content|wp-includes|wp-json|cdn-cgi|idx|feed)/")


def to_root_relative(value):
    """Store asset paths root-relative (no ../); generate_agents re-prefixes per depth."""
    return _STRIP_DOTS.sub(r"\1/", value) if value else value


def main():
    agents = []
    missing = []
    sources = [(slug, os.path.join(ROOT, slug, "index.html")) for slug in agent_slugs()]
    sources += [(slug, os.path.join(ROOT, fn)) for slug, fn in ROOT_FILE_AGENTS.items()]

    for slug, path in sorted(sources):
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8", errors="replace") as f:
            html = f.read()
        rec = extract(slug, html)
        for k in ("photo", "photo_srcset", "bio_html"):
            rec[k] = to_root_relative(rec.get(k))
        agents.append(rec)
        gaps = [k for k in ("name", "title", "photo", "bio_html") if not rec.get(k)]
        if gaps:
            missing.append((slug, gaps))

    out = os.path.join(ROOT, "_build", "agents.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(agents, f, indent=2, ensure_ascii=False)

    print(f"Extracted {len(agents)} agents -> {out}")
    if missing:
        print(f"\n{len(missing)} agents with missing fields (need manual review):")
        for slug, gaps in missing:
            print(f"  {slug}: missing {', '.join(gaps)}")
    else:
        print("All agents have name/title/photo/bio.")

if __name__ == "__main__":
    sys.exit(main())
